LABELS_BY_GROUP_NAME = {
    "adsk_3dsmax": "3ds Max",
    "aftereffects": "After Effects",
    "blender": "Blender",
    "celaction": "Celaction 2D",
    "cinema4d": "Cinema4D",
    "equalizer": "3DEqualizer",
    "flame": "Flame",
    "fusion": "Fusion",
    "harmony": "Harmony",
    "hiero": "Hiero",
    "houdini": "Houdini",
    "maya": "Maya",
    "motionbuilder": "Motion Builder",
    "nuke": "Nuke",
    "nukeassist": "Nuke Assist",
    "nukestudio": "Nuke Studio",
    "nukex": "Nuke X",
    "openrv": "OpenRV",
    "photoshop": "Photoshop",
    "premiere": "Premiere",
    "resolve": "Resolve",
    "substancepainter": "Substance Painter",
    "substancedesigner": "Substance Designer",
    "terminal": "Terminal",
    "tvpaint": "TVPaint",
    "unreal": "Unreal Editor",
    "wrap": "Wrap",
    "zbrush": "Zbrush",
    "mochapro": "Mocha Pro",
}
ICONS_BY_GROUP_NAME = {
    "adsk_3dsmax": "3dsmax.png",
    "aftereffects": "aftereffects.png",
    "blender": "blender.png",
    "celaction": "celaction.png",
    "cinema4d": "cinema4d.png",
    "equalizer": "3de4.png",
    "flame": "flame.png",
    "fusion": "fusion.png",
    "harmony": "harmony.png",
    "hiero": "hiero.png",
    "houdini": "houdini.png",
    "maya": "maya.png",
    "motionbuilder": "motionbuilder.png",
    "nuke": "nuke.png",
    "nukeassist": "nuke.png",
    "nukestudio": "nukestudio.png",
    "nukex": "nukex.png",
    "openrv": "openrv.png",
    "photoshop": "photoshop.png",
    "resolve": "resolve.png",
    "substancepainter": "substancepainter.png",
    "substancedesigner": "substancedesigner.png",
    "tvpaint": "tvpaint.png",
    "unreal": "ue4.png",
    "wrap": "wrap.png",
    "zbrush": "zbrush.png",
    "mochapro": "mochapro.png",
}
