APP_LABELS_BY_GROUP = {
    "adsk_3dsmax": "Autodesk 3ds Max",
    "aftereffects": "Adobe After Effects",
    "blender": "Blender",
    "celaction": "Celaction 2D",
    "equalizer": "3DEqualizer",
    "flame": "Autodesk Flame",
    "fusion": "Fusion",
    "harmony": "Harmony",
    "hiero": "Hiero",
    "houdini": "Houdini",
    "maya": "Autodesk Maya",
    "motionbuilder": "Motion Builder",
    "nuke": "Nuke",
    "nukeassist": "Nuke Assist",
    "nukestudio": "Nuke Studio",
    "nukex": "Nuke X",
    "openrv": "OpenRV",
    "photoshop": "Adobe Photoshop",
    "resolve": "Resolve",
    "substancepainter": "Substance Painter",
    "tvpaint": "TVPaint",
    "unreal": "Unreal Editor",
    "wrap": "Wrap",
    "zbrush": "Zbrush",
}
